# fly.toml app configuration file generated for nepxy-staging-misty-pond-1887 on 2026-01-17T15:42:13-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nepxy-staging'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    method = 'GET'
    path = '/healthz'
    protocol = 'http'
    grace_period = '10s'
  [[http_service.checks]]
    interval = '30s'
    timeout = '2s'
    method = 'GET'
    path = '/readyz'
    protocol = 'http'
    grace_period = '20s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
